# Generated by Django 5.2.5 on 2025-08-29 01:21

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aboutfivemodel_aboutservicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagline', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('sec_title', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
